import express from 'express';
import { adminDb } from '../firebaseAdmin.js';
import { verifyFirebaseToken } from '../middleware/verifyFirebaseToken.js';
import { loadUserProfile } from '../middleware/loadUserProfile.js';
import { aiConfig } from '../ai/aiConfig.js';
import { runGeminiTextPrompt, generateGeminiText, discoverGeminiModels, selectWorkingGeminiModel } from '../ai/geminiProvider.js';
import { validateMaterialAccess } from '../ai/materialAccessHelper.js';
import { fetchR2ObjectAsBuffer } from '../ai/r2InternalFetcher.js';
import { extractTextFromPdfBuffer } from '../ai/pdfTextExtractor.js';
import { generateAcademicAiOutput, getIndiaDateKey } from '../ai/academicAiService.js';

const router = express.Router();

/**
 * GET /api/ai/health
 * Checks that the backend AI foundation is registered and active.
 */
router.get('/health', (req, res) => {
  res.json({ 
    ok: true,
    aiModule: "enabled",
    provider: aiConfig.provider,
    hasProviderKey: aiConfig.hasGeminiKey,
    academicPrimaryModel: "gemini-3.1-flash-lite",
    academicFallbackModel: "gemini-3.5-flash",
    message: "AI backend foundation is ready."
  });
});

// Helper to check if the user is an active administrator
function isAdmin(userProfile) {
  const role = userProfile && userProfile.role;
  const status = userProfile && (userProfile.status || userProfile.accountStatus || 'active');
  return role === 'admin' && status === 'active';
}

// Helper to check if the user is an active faculty or admin
function isFacultyOrAdmin(userProfile) {
  const role = userProfile && userProfile.role;
  const status = userProfile && (userProfile.status || userProfile.accountStatus || 'active');
  return (role === 'admin' || role === 'faculty') && status === 'active';
}

/**
 * GET /api/ai/quota-status
 * Checks the user's current AI daily quota status.
 */
router.get('/quota-status', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    const user = req.userProfile;
    if (user.role !== 'student') {
      return res.json({
        ok: true,
        role: user.role,
        message: `${user.role === 'admin' ? 'Admin diagnostics' : 'Faculty AI generation tools'} are not counted against student AI quota.`
      });
    }

    const dateKey = getIndiaDateKey();
    const docRef = adminDb.collection('aiUsageDaily').doc(`${req.uid}_${dateKey}`);
    const doc = await docRef.get();
    
    const used = doc.exists ? doc.data().used : { pdf_summary: 0, important_questions: 0 };
    const limits = aiConfig.studentDailyLimits;
    const remaining = {
      pdf_summary: Math.max(0, limits.pdf_summary - used.pdf_summary),
      important_questions: Math.max(0, limits.important_questions - used.important_questions)
    };

    res.json({
      ok: true,
      role: 'student',
      dateKey,
      timezone: 'Asia/Kolkata',
      limits,
      used,
      remaining
    });
  } catch (err) {
    console.error('[AI Quota Status Fail]', err);
    res.status(500).json({ ok: false, message: 'Failed to fetch quota status.' });
  }
});

/**
 * GET /api/ai/history
 * Returns the AI outputs history generated by the authenticated student
 * and verified that the student still has permission to access the associated materials.
 */
router.get('/history', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    const user = req.userProfile;
    if (!user) {
      return res.status(401).json({ ok: false, message: "Unauthenticated." });
    }
    
    if (user.role !== 'student') {
      return res.status(403).json({
        ok: false,
        message: "AI history is currently only available for students."
      });
    }

    const { action, limit = 20 } = req.query;
    const limitNum = Math.min(50, parseInt(limit, 10) || 20);

    // Fetch outputs generated by this student
    let query = adminDb.collection('aiOutputs').where('generatedBy', '==', req.uid);
    if (action && action !== 'all') {
      query = query.where('action', '==', action);
    }

    const snapshot = await query.get();
    const items = [];

    for (const doc of snapshot.docs) {
      const data = doc.data();
      
      // Perform security and accessibility verification on the material
      const accessResult = await validateMaterialAccess(user, data.materialId);
      if (!accessResult.authorized) {
        // Skip materials that are no longer accessible, deleted, or from another department
        continue;
      }

      const { material } = accessResult;

      items.push({
        id: doc.id,
        materialId: data.materialId,
        materialTitle: material.title || data.materialTitle || "Untitled Study Material",
        materialType: material.fileType || material.type || "PDF DOCUMENT",
        subject: material.subject || "Academic Study",
        semester: material.semester || "N/A",
        year: material.year || "N/A",
        department: material.department || "N/A",
        action: data.action,
        actionLabel: data.action === 'pdf_summary' ? 'PDF Summary' : 'Important Questions',
        outputPreview: data.output ? data.output.substring(0, 150) + "..." : "",
        output: data.output || "",
        cached: true,
        cacheSource: "fresh-cache",
        modelUsed: data.model || "gemini-3.1-flash-lite",
        createdAt: data.generatedAt ? (data.generatedAt.toDate ? data.generatedAt.toDate().toISOString() : data.generatedAt) : new Date().toISOString(),
        updatedAt: data.generatedAt ? (data.generatedAt.toDate ? data.generatedAt.toDate().toISOString() : data.generatedAt) : new Date().toISOString()
      });
    }

    // Sort items by createdAt descending (most recent first)
    items.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

    // Paginate in memory up to limit
    const paginatedItems = items.slice(0, limitNum);

    res.json({
      ok: true,
      items: paginatedItems,
      count: paginatedItems.length
    });
  } catch (err) {
    console.error('[GET /api/ai/history Fail]', err);
    res.status(500).json({ 
      ok: false, 
      code: "HISTORY_FETCH_FAILED",
      message: 'Failed to fetch AI output history.' 
    });
  }
});

/**
 * GET /api/ai/history/:id
 * Retrieves a single saved AI output after strict ownership and material access checks.
 */
router.get('/history/:id', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    const user = req.userProfile;
    if (!user) {
      return res.status(401).json({ ok: false, message: "Unauthenticated." });
    }

    if (user.role !== 'student') {
      return res.status(403).json({
        ok: false,
        message: "AI history is currently only available for students."
      });
    }

    const { id } = req.params;
    const doc = await adminDb.collection('aiOutputs').doc(id).get();
    if (!doc.exists) {
      return res.status(404).json({
        ok: false,
        message: "The requested AI output history record was not found."
      });
    }

    const data = doc.data();

    // Verify ownership
    if (data.generatedBy !== req.uid) {
      return res.status(403).json({
        ok: false,
        message: "You are not authorized to view this saved AI output."
      });
    }

    // Verify current access to material
    const accessResult = await validateMaterialAccess(user, data.materialId);
    if (!accessResult.authorized) {
      return res.status(403).json({
        ok: false,
        message: "You no longer have permission to access the material associated with this AI output."
      });
    }

    const { material } = accessResult;

    res.json({
      ok: true,
      item: {
        id: doc.id,
        materialId: data.materialId,
        materialTitle: material.title || data.materialTitle || "Untitled Study Material",
        materialType: material.fileType || material.type || "PDF DOCUMENT",
        subject: material.subject || "Academic Study",
        semester: material.semester || "N/A",
        year: material.year || "N/A",
        department: material.department || "N/A",
        action: data.action,
        actionLabel: data.action === 'pdf_summary' ? 'PDF Summary' : 'Important Questions',
        output: data.output || "",
        cached: true,
        cacheSource: "fresh-cache",
        modelUsed: data.model || "gemini-3.1-flash-lite",
        createdAt: data.generatedAt ? (data.generatedAt.toDate ? data.generatedAt.toDate().toISOString() : data.generatedAt) : new Date().toISOString()
      }
    });
  } catch (err) {
    console.error('[GET /api/ai/history/:id Fail]', err);
    res.status(500).json({
      ok: false,
      message: "An error occurred while retrieving the saved AI output details."
    });
  }
});

/**
 * POST /api/ai/extract-pdf-text-test
 * Secure, internal backend-only PDF text extraction test.
 * Restricted to active administrators and faculty members only.
 */
router.post('/extract-pdf-text-test', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    if (!isFacultyOrAdmin(req.userProfile)) {
      return res.status(403).json({
        ok: false,
        message: "Only active faculty members and administrators can execute the PDF text extraction test."
      });
    }

    const { materialId } = req.body || {};
    if (!materialId) {
      return res.status(400).json({
        ok: false,
        message: "Missing required parameter 'materialId' in request body."
      });
    }

    // Step 1: Validate material access permissions
    const accessResult = await validateMaterialAccess(req.userProfile, materialId);
    if (!accessResult.authorized) {
      console.warn(`[AI Extraction Access Denied] User: ${req.user.uid}, Material: ${materialId}, Code: ${accessResult.code}`);
      return res.status(403).json({
        ok: false,
        code: accessResult.code,
        message: accessResult.message || "Access denied."
      });
    }

    const { material, storagePath } = accessResult;

    // Step 2: Retrieve binary from private Cloudflare R2
    let pdfBuffer;
    try {
      pdfBuffer = await fetchR2ObjectAsBuffer(storagePath);
    } catch (fetchErr) {
      console.error(`[AI Extraction Fetch Fail] Material: ${materialId}`, fetchErr.message);
      return res.status(502).json({
        ok: false,
        code: "R2_OBJECT_NOT_FOUND",
        message: `Failed to retrieve PDF from private R2 storage. Ensure storagePath is valid: ${fetchErr.message}`
      });
    }

    // Step 3: Perform PDF text extraction
    try {
      const extraction = await extractTextFromPdfBuffer(pdfBuffer, {
        maxPdfChars: 20000 // Limit extraction buffer size for testing
      });

      if (!extraction.hasText) {
        return res.status(422).json({
          ok: false,
          code: "PDF_TEXT_EMPTY",
          message: "No indexable/parsable text was found inside this PDF. It may be scanned or image-only."
        });
      }

      // Generate a limited preview of the extracted text (max 1000 characters)
      const previewText = extraction.text.substring(0, 1000);

      console.log(`[AI Extraction Success] Material: ${materialId}, Chars Extracted: ${extraction.extractedChars}, Pages: ${extraction.pageCount}`);

      let message = "PDF text extraction successful.";
      if (extraction.quality && !extraction.quality.aiUsable) {
        message = "PDF decoded, but extracted text quality is too low for reliable AI use.";
      }

      return res.json({
        ok: true,
        materialId,
        title: material.title || "Untitled Study Material",
        pageCount: extraction.pageCount,
        extractedChars: extraction.extractedChars,
        truncated: extraction.truncated,
        previewText,
        quality: extraction.quality,
        message
      });
    } catch (parseErr) {
      console.error(`[AI Extraction Parse Fail] Material: ${materialId}`, parseErr.message);
      return res.status(502).json({
        ok: false,
        code: "PDF_PARSE_FAILED",
        message: `PDF text parser failed to compile or decode binary pages: ${parseErr.message}`
      });
    }

  } catch (error) {
    console.error('[AI Extraction Route Error]:', error);
    return res.status(500).json({
      ok: false,
      code: "INTERNAL_ERROR",
      message: "An internal server error occurred during PDF text extraction."
    });
  }
});

/**
 * POST /api/ai/material-quality
 * Retrieves text extraction quality metrics for the requested material.
 * Accessible to any authenticated student, faculty, or admin who has access to the material.
 */
router.post('/material-quality', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    const { materialId } = req.body || {};
    if (!materialId) {
      return res.status(400).json({
        ok: false,
        code: "MISSING_MATERIAL_ID",
        message: "Missing required parameter 'materialId' in request body.",
        stage: "material_lookup"
      });
    }

    // Step 1: Validate material access permissions
    const accessResult = await validateMaterialAccess(req.userProfile, materialId);
    if (!accessResult.authorized) {
      let status = 403;
      if (accessResult.code === 'MATERIAL_NOT_FOUND') {
        status = 404;
      } else if (accessResult.code === 'MATERIAL_NOT_ACTIVE') {
        status = 400; // or 409
      } else if (accessResult.code === 'STORAGE_PROVIDER_UNSUPPORTED') {
        status = 400;
      }
      return res.status(status).json({
        ok: false,
        code: accessResult.code,
        message: accessResult.message || "Access denied.",
        stage: "access_validation"
      });
    }

    const { material, storagePath } = accessResult;

    // Step 2: Check database caches first
    if (adminDb) {
      try {
        const summaryCache = await adminDb.collection('aiOutputs').doc(`${materialId}_pdf_summary`).get();
        if (summaryCache.exists) {
          const cacheData = summaryCache.data();
          if (cacheData && cacheData.quality) {
            const isPoorQuality = cacheData.quality && !cacheData.quality.aiUsable;
            return res.json({
              ok: true,
              materialId,
              title: material.title || cacheData.materialTitle || "Untitled",
              pageCount: cacheData.pageCount || null,
              extractedChars: cacheData.extractedChars || 0,
              truncated: !!cacheData.truncated,
              quality: cacheData.quality,
              message: isPoorQuality 
                ? "PDF decoded, but extracted text quality is too low for reliable AI use."
                : "PDF quality check completed."
            });
          }
        }

        const questionsCache = await adminDb.collection('aiOutputs').doc(`${materialId}_important_questions`).get();
        if (questionsCache.exists) {
          const cacheData = questionsCache.data();
          if (cacheData && cacheData.quality) {
            const isPoorQuality = cacheData.quality && !cacheData.quality.aiUsable;
            return res.json({
              ok: true,
              materialId,
              title: material.title || cacheData.materialTitle || "Untitled",
              pageCount: cacheData.pageCount || null,
              extractedChars: cacheData.extractedChars || 0,
              truncated: !!cacheData.truncated,
              quality: cacheData.quality,
              message: isPoorQuality 
                ? "PDF decoded, but extracted text quality is too low for reliable AI use."
                : "PDF quality check completed."
            });
          }
        }
      } catch (cacheErr) {
        console.warn('[AI Quality Route Cache Read Fail] Bypassing cache checks:', cacheErr.message);
      }
    }

    // Step 3: Fetch R2 PDF & run text quality checks
    let pdfBuffer;
    try {
      pdfBuffer = await fetchR2ObjectAsBuffer(storagePath);
    } catch (fetchErr) {
      console.error(`[AI Quality Route Fetch Fail] Material: ${materialId}`, fetchErr);
      return res.status(404).json({
        ok: false,
        code: "R2_OBJECT_NOT_FOUND",
        message: `Failed to fetch PDF resource from Cloudflare R2: ${fetchErr.message}`,
        stage: "r2_fetch"
      });
    }

    let extraction;
    try {
      extraction = await extractTextFromPdfBuffer(pdfBuffer, {
        maxPdfChars: 20000
      });
    } catch (parseErr) {
      console.error(`[AI Quality Route Parser Fail] Material: ${materialId}`, parseErr);
      return res.status(422).json({
        ok: false,
        code: "PDF_PARSE_FAILED",
        message: `Failed to parse PDF binary content: ${parseErr.message}`,
        stage: "pdf_extract"
      });
    }

    if (!extraction.hasText) {
      return res.status(422).json({
        ok: false,
        code: "PDF_TEXT_EMPTY",
        message: "The PDF contains no indexable text layer. It might be an un-scanned image.",
        stage: "pdf_extract"
      });
    }

    const isPoorQuality = extraction.quality && !extraction.quality.aiUsable;
    const msg = isPoorQuality 
      ? "PDF decoded, but extracted text quality is too low for reliable AI use."
      : "PDF quality check completed.";

    return res.json({
      ok: true,
      materialId,
      title: material.title || "Untitled",
      pageCount: extraction.pageCount || null,
      extractedChars: extraction.extractedChars || 0,
      truncated: !!extraction.truncated,
      quality: extraction.quality,
      message: msg
    });

  } catch (error) {
    console.error('[AI Quality Route Error]:', error);
    return res.status(500).json({
      ok: false,
      code: "INTERNAL_ERROR",
      message: "An internal server error occurred while retrieving PDF quality statistics.",
      stage: "quality_analysis"
    });
  }
});

/**
 * POST /api/ai/material-summary
 * Generates an academic summary for the requested material.
 * Accessible to any authenticated student, faculty, or admin who has access to the material.
 */
router.post('/material-summary', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    const { materialId } = req.body || {};
    if (!materialId) {
      return res.status(400).json({
        ok: false,
        code: "MISSING_MATERIAL_ID",
        message: "Missing required parameter 'materialId' in request body."
      });
    }

    const result = await generateAcademicAiOutput({
      uid: req.uid,
      role: req.userProfile.role,
      userProfile: req.userProfile
    }, materialId, 'pdf_summary');
    return res.json(result);
  } catch (err) {
    console.error(`[AI Summary Route Error] Material ${req.body?.materialId}:`, err);
    
    const status = err.status || 500;
    return res.status(status).json({
      ok: false,
      code: err.code || "INTERNAL_ERROR",
      message: err.message || "An internal error occurred during summary generation.",
      retryable: err.retryable !== undefined ? err.retryable : false,
      stage: err.stage || "provider_generation",
      quality: err.quality || null,
      modelsAttempted: err.modelsAttempted || null
    });
  }
});

/**
 * POST /api/ai/important-questions
 * Generates academic study questions for the requested material.
 * Accessible to any authenticated student, faculty, or admin who has access to the material.
 */
router.post('/important-questions', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    const { materialId } = req.body || {};
    if (!materialId) {
      return res.status(400).json({
        ok: false,
        code: "MISSING_MATERIAL_ID",
        message: "Missing required parameter 'materialId' in request body."
      });
    }

    const result = await generateAcademicAiOutput({
      uid: req.uid,
      role: req.userProfile.role,
      userProfile: req.userProfile
    }, materialId, 'important_questions');
    return res.json(result);
  } catch (err) {
    console.error(`[AI Important Questions Route Error] Material ${req.body?.materialId}:`, err);
    
    const status = err.status || 500;
    return res.status(status).json({
      ok: false,
      code: err.code || "INTERNAL_ERROR",
      message: err.message || "An internal error occurred during questions generation.",
      retryable: err.retryable !== undefined ? err.retryable : false,
      stage: err.stage || "provider_generation",
      quality: err.quality || null,
      modelsAttempted: err.modelsAttempted || null
    });
  }
});

/**
 * POST /api/ai/smoke-test
 * Performs a highly restricted connectivity check against Google Gemini.
 * Strictly restricted to active Administrators only.
 */
router.post('/smoke-test', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    if (!isAdmin(req.userProfile)) {
      return res.status(403).json({
        ok: false,
        message: "Only active administrators can execute the backend AI connectivity smoke test."
      });
    }

    if (!aiConfig.hasGeminiKey) {
      return res.status(200).json({
        ok: false,
        message: "Gemini API key is not configured on the backend."
      });
    }

    // Explicitly enforce static non-sensitive test prompt.
    // Disallow arbitrary, client-controlled payloads.
    const smokeTestPrompt = "Reply with exactly: AI backend configured.";

    const result = await runGeminiTextPrompt({ prompt: smokeTestPrompt });

    if (result.ok) {
      return res.json({
        ok: true,
        message: "AI smoke connectivity test successful.",
        response: result.text ? result.text.trim() : null,
        modelUsed: result.modelUsed
      });
    } else {
      return res.status(502).json({
        ok: false,
        message: result.message || "Failed to communicate with Gemini AI.",
        errorType: result.errorType
      });
    }
  } catch (error) {
    console.error('[AI Smoke Test Error]:', error);
    return res.status(500).json({
      ok: false,
      message: "An internal server error occurred during the AI smoke test."
    });
  }
});

/**
 * GET /api/ai/models-diagnostic
 * Returns configurations of default and fallback models.
 * Strictly restricted to active Administrators only.
 */
router.get('/models-diagnostic', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    if (!isAdmin(req.userProfile)) {
      return res.status(403).json({
        ok: false,
        message: "Only active administrators can access the AI models diagnostic information."
      });
    }

    const discovery = await discoverGeminiModels();
    if (!discovery.ok) {
      return res.status(502).json({
        ok: false,
        code: "MODEL_DISCOVERY_FAILED",
        message: discovery.message || "Could not list Gemini models with the current backend SDK or API key.",
        discoverySupported: discovery.supported
      });
    }

    const selection = await selectWorkingGeminiModel();

    const envModel = process.env.GEMINI_MODEL ? String(process.env.GEMINI_MODEL).trim() : null;
    const prioritizedModelsAttempted = [];
    if (envModel) {
      prioritizedModelsAttempted.push(envModel);
    }
    if (!prioritizedModelsAttempted.includes("gemini-3.1-flash-lite")) {
      prioritizedModelsAttempted.push("gemini-3.1-flash-lite");
    }
    if (!prioritizedModelsAttempted.includes("gemini-3.5-flash")) {
      prioritizedModelsAttempted.push("gemini-3.5-flash");
    }

    res.json({
      ok: true,
      hasProviderKey: aiConfig.hasGeminiKey,
      configuredModel: envModel || "Not set",
      academicPrimaryModel: "gemini-3.1-flash-lite",
      academicFallbackModel: "gemini-3.5-flash",
      selectedModel: selection.modelId,
      availableTextModels: selection.availableTextModels || [],
      modelsAttempted: prioritizedModelsAttempted,
      discoverySupported: selection.discoverySupported,
      message: "Gemini model diagnostics completed safely."
    });
  } catch (error) {
    console.error('[AI Diagnostic Route Error]:', error);
    res.status(500).json({
      ok: false,
      message: "An error occurred retrieving AI diagnostics info."
    });
  }
});

/**
 * POST /api/ai/model-generate-diagnostic
 * Runs the shared generateGeminiText function with a static prompt to verify models.
 * Strictly restricted to active Administrators only.
 */
router.post('/model-generate-diagnostic', verifyFirebaseToken, loadUserProfile, async (req, res) => {
  try {
    if (!isAdmin(req.userProfile)) {
      return res.status(403).json({
        ok: false,
        message: "Only active administrators can execute the model generate diagnostic."
      });
    }

    if (!aiConfig.hasGeminiKey) {
      return res.status(200).json({
        ok: false,
        message: "Gemini API key is not configured on the backend."
      });
    }

    const testPrompt = "Reply with exactly: model diagnostic ok.";

    const result = await generateGeminiText({
      prompt: testPrompt,
      purpose: "smoke-test",
      maxOutputTokens: 50
    });

    if (result.ok) {
      return res.json({
        ok: true,
        response: result.text ? result.text.trim() : "model diagnostic ok.",
        modelUsed: result.modelUsed,
        modelsAttempted: result.modelsAttempted || [result.modelUsed]
      });
    } else {
      return res.status(502).json({
        ok: false,
        message: "Failed to communicate with Gemini AI."
      });
    }
  } catch (error) {
    console.error('[AI Model Diagnostic Error]:', error);
    const code = error.code || "INTERNAL_ERROR";
    const status = (code === "PROVIDER_RATE_LIMIT" || code === "PROVIDER_QUOTA_EXCEEDED") ? 429 
                 : (code === "PROVIDER_HIGH_DEMAND" || code === "GEMINI_API_KEY_MISSING") ? 503 
                 : 502;
    return res.status(status).json({
      ok: false,
      code,
      message: error.message || "An internal server error occurred during the model generate diagnostic.",
      retryable: error.retryable !== undefined ? error.retryable : false,
      stage: error.stage || "provider_generation",
      modelsAttempted: error.modelsAttempted || []
    });
  }
});

export default router;
